baseURL = "http://dasher-site.netlify.com"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Dasher"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/dasher-project/website/edit/master/content/"
  description = "Dasher"
  author = "dasher-project"
  showVisitedLinks = false
  themeVariant = "dasher"
  ordersectionsby = 'weight'
  
[outputs]
home = [ "HTML", "RSS", "JSON"]



[Languages]
[Languages.en]
title = "Dasher (English)"
weight = 1
languageName = "English"



[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-archive'></i> Original Inference Group site"
url = "/dasher/"
weight = 0


[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/dasher-project/dasher"
weight = 10


[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bookmark'></i> Developer Documentation"
identifier = "hugodoc"
url = "https://developer.dasher.zone/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[Languages.fr]
title = "Documentation du thème Hugo Learn"
weight = 2
languageName = "Français"

[[Languages.fr.menu.shortcuts]]
name = "<i class='fa fa-fw fa-github'></i> Repo Github"
identifier = "ds"
url = "https://github.com/dasher-project/dasher"
weight = 10


[[Languages.fr.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bookmark'></i> Developer Hugo"
identifier = "hugodoc"
url = "https://developer.dasher.zone/"
weight = 20

[[Languages.fr.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Crédits"
url = "/credits"
weight = 30
